<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Sales.aspx.cs" Inherits="ShopManagement.Item.Sales" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="form-horizontal">
        <hr />
        <asp:HiddenField ID="IdHiddenField" runat="server" />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <asp:Label runat="server" ID="lblItemCode" AssociatedControlID="txtItemcode" CssClass="col-md-2 control-label">Item Code</asp:Label>
                <asp:TextBox runat="server" ID="txtItemcode" CssClass="form-control" TextMode="Number" AutoPostBack="true" OnTextChanged="txtItemcode_TextChanged" />
                <asp:Label runat="server" ID="lblShowQty" AssociatedControlID="lblShowQty" CssClass="col-md-2 control-label" Style="color:red">00</asp:Label>
            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <asp:GridView ID="ItemSalesGridView" runat="server" EmptyDataText="No Order Available Here" Width="100%" CssClass="table table-striped table-bordered table-hover" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="10" ForeColor="Black" GridLines="Horizontal" AllowPaging="false" CellSpacing="10" OnRowDeleting="ItemSalesGridView_RowDeleting" OnRowCancelingEdit="ItemSalesGridView_RowCancelingEdit" OnRowEditing="ItemSalesGridView_RowEditing" OnRowUpdating="ItemSalesGridView_RowUpdating" OnRowDataBound="ItemSalesGridView_RowDataBound">
                    <Columns>
                        <asp:TemplateField HeaderText="Name">
                            <ItemTemplate>
                                <asp:Label ID="lblItem" runat="server" Text='<%#Eval("Item") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEItem" runat="server" Text='<%#Eval("Item") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Qty">
                            <ItemTemplate>
                                <asp:Label ID="lblQty" runat="server" Text='<%#Eval("Qty") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEQty" runat="server" Text='<%#Eval("Qty") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Unit">
                            <ItemTemplate>
                                <asp:Label ID="lblUnit" runat="server" Text='<%#Eval("Unit") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtEUnit" runat="server" Text='<%#Eval("Unit") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Total">
                            <ItemTemplate>
                                <asp:Label ID="lblTotal" runat="server" Text='<%#Eval("Total") %>'></asp:Label>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtETotal" runat="server" Text='<%#Eval("Total") %>'></asp:TextBox>
                            </EditItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <PagerStyle Font-Bold="true" Font-Size="Small" ForeColor="#3399FF" />
                </asp:GridView>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-2">
                <asp:Label runat="server" ID="lblInvoice" AssociatedControlID="txtInvoice" CssClass="control-label">Invoice</asp:Label>
                <asp:TextBox runat="server" ID="txtInvoice" CssClass="form-control" style="text-align:center" Font-Bold="true" Font-Size="Medium" TextMode="Number" ReadOnly="true" />
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblGrandTotal" AssociatedControlID="txtGrandTotal" CssClass="control-label">Grand Total</asp:Label>
                <asp:TextBox runat="server" ID="txtGrandTotal" CssClass="form-control" style="text-align:center" Font-Bold="true" Font-Size="Medium" ReadOnly="true" />
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblDiscount" AssociatedControlID="txtPayableAmount" CssClass="control-label">Discount(%)</asp:Label>
                <asp:TextBox runat="server" ID="txtDiscount" CssClass="form-control" Font-Bold="true" style="text-align:center" Font-Size="Medium" TextMode="Number" AutoPostBack="true" OnTextChanged="txtDiscount_TextChanged" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-2">
                <asp:Label runat="server" ID="lblPayableAmount" AssociatedControlID="txtInvoice" CssClass="control-label">Payable Amount</asp:Label>
                <asp:TextBox runat="server" ID="txtPayableAmount" CssClass="form-control" ReadOnly="true" style="text-align:center" Font-Bold="true" Font-Size="Medium"/>
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblPaidAmount" AssociatedControlID="txtGrandTotal" CssClass="control-label">Paid Amount</asp:Label>
                <asp:TextBox runat="server" ID="txtPaidAmount" CssClass="form-control" TextMode="Number" style="text-align:center" Font-Bold="true" Font-Size="Medium" AutoPostBack="true" OnTextChanged="txtPaidAmount_TextChanged" />
            </div>
            <div class="col-md-2">
                <asp:Label runat="server" ID="lblChanges" AssociatedControlID="txtPayableAmount" CssClass="control-label">Changes Amount</asp:Label>
                <asp:TextBox runat="server" ID="txtChanges" CssClass="form-control" ReadOnly="true" style="text-align:center" Font-Bold="true" Font-Size="Medium" />
            </div>
        </div>
    </div>
</asp:Content>
